export default function Content() {
  return (
    <>
      <p>Rules for Email etiquette and online reputation</p>
      <ul>
        <li><strong>Rule 1 – Answer Swiftly:</strong> Your customers send you email because they want quick responses. The golden rule for email is to reply within 24 hours, and preferably within the same working day. If your response email is complicated, just send an email confirming receipt and letting them know that you will get back to them.</li>
        <li><strong>Rule 2 – Use a Meaningful Subject Line:</strong> Try to use a subject that is meaningful to the recipient as well as yourself. For instance, when you send an email about a product, it is better to mention the actual name of the product, e.g. 'Product A information' than to just say 'Product information'.</li>
        <li><strong>Rule 3 – Don't Abuse the "Reply to All":</strong> Only use Reply to All if you really need your message to be seen by each person who received the original message. Sending off irrelevant or unnecessary replies to everyone on the list is just annoying and confusing.</li>
        <li><strong>Rule 4 – Use the Bcc Field:</strong> When sending to many people, some people put all the email addresses in the To: field. There are two drawbacks to doing that: (1) the recipient knows that you have sent the same message to a large number of recipients, and (2) you are publicizing someone else's email address without their permission. Instead, consider using the Bcc: field. Put your mailing list group name in To: field in their email (leaving the To: field blank may look like spam). If you have Microsoft Outlook and Word you can do a mail merge so each recipient receives their own email, or create a mailing group in your email software if it has that utility. Never send emails to customers in group emails as the content must be approved by the HO.</li>
        <li><strong>Rule 5 – Don't Leave Out the Message Thread:</strong> Include the original mail in your reply, in other words click 'Reply', instead of 'New Mail'. We all receive many emails and we can't remember each individual email.</li>
        <li><strong>Rule 6 – Read Your Email Before You Send It:</strong> Treat email like any other official company document. Read it before you send it. Spelling and grammar errors can create a very poor impression on the company. Look out for potential misunderstandings, the tone, and inappropriate comments.</li>
        <li><strong>Rule 7 – Confidential Information:</strong> Email is just too risky a place to include confidential information. Ask yourself if you would want the content of your email displayed on a bulletin board. Never make libelous, sexist or racially discriminating comments in emails, even as a joke. Consider implementing a Disclaimer on the bottom of all corporate emails with statements on Breach of Confidentiality, Virus Liability, etc. (Yes, you can be sued for sending an email that contains a virus!)</li>
        <li><strong>Rule 8 – Abbreviations & Emoticons:</strong> Be careful using email abbreviations such as BTW (by the way) and LOL (laugh out loud) in business emails. The same goes for emoticons, such as the smiley :-). A lot of people don't know what they mean, and moreover they are good when they are used in your personal emails.</li>
        <li><strong>Rule 9 – Don't Attach Unnecessary Files:</strong> Wherever possible try to compress attachments and only send attachments when they are productive. Make sure you have good virus software in place to scan your outgoing emails – a customer would not be happy if you send them documents riddled with viruses!</li>
        <li><strong>Rule 10 – Don't Forward Junk:</strong> Don't forward chain letters, virus hoaxes, chain email solicitations for charitable causes even if they sound bonafide, funny pictures and jokes. Would you put these things on your corporate letterhead? I don't think so. Don't ever send or forward emails containing libelous, defamatory, offensive, racist or obscene remarks. Just one offensive remark can result in a multi-million dollar court case for you and your company.</li>
        <li><strong>Rule 11 – Be Concise:</strong> Do not make an email longer than it needs to be. Email is harder to read than printed communications. A long email can be very discouraging and can be abandoned before the recipient gets to your final point all the way down at the bottom. If it has to be long, consider including a synopsis at the top of the email.</li>
        <li><strong>Rule 12 – Answer All Questions & More:</strong> Make sure you answer all the questions and pre-empt new questions in your reply. If you don't answer all the questions in the original email, you're wasting your own, your company's and your customer's time. Worse still, you are leaving the customer frustrated. By answering all questions and pre-empting further inquiries, you are making a great impression and reflecting thoughtful customer service. For example, a question regarding the types of credit cards you accept can be replied to with the list of cards, information on other payment methods and even a link to your website order information page!</li>
        <li><strong>Rule 13 – Make It Personal:</strong> Did you know that the most effective word in marketing is "you"? Not only should the e-mail be personally addressed, it should also include personal, i.e. customized, content. For this reason auto replies are usually not very effective. When you get some questions over and over, such as directions to your office or how to subscribe to your newsletter, save these texts as response templates and paste them into your message when you need them. You can save your templates in a Word document, or use pre-formatted emails.</li>
        <li><strong>Rule 14 – Use the Proper Structure & Layout:</strong> Reading from a screen is more difficult than reading from paper so the structure and layout is very important for email messages. Make your paragraphs short and use blank lines between each paragraph. When making points, number them or separate each point with blank lines to keep the overview.</li>
        <li><strong>Rule 22 – Keep Your Language Gender Neutral:</strong> It is correct today to avoid sexist language such as: "The customer should bring his car to our service department for an oil change." You can use "his/her" or keep it neutral by rephrasing the sentence: "The customer should bring the car to our service department for an oil change".</li>
        <li><strong>Rule 23 – Don't Reply to Spam:</strong> Spam may make you furious and you may want to reply with "flame mail". Many spam emails are sent to confirm that your email address is still valid, and by replying you are only making yourself known to dubious marketers which may result in even more spam. Just delete the spam, or use anti-spam software.</li>
      </ul>
      <h2>Email Signature</h2>
      <p>Contact the YumPOS team for your corporate email signature.</p>
      <h2>Online Reputation</h2>
      <p>Please do not get involved into any kind of online classified listings or blog postings or any postings anywhere on the web as STUDIO 11 is highly concerned about its online reputation. Our marketing department handles the Facebook postings and other online requirements centrally so that our brand uniqueness is maintained. You can always share the posts created by the company or contact marketing department should you want to post anything on Facebook for content and creative support.</p>
    </>
  );
}
